name: Build Code, Run unit test, Run SAST, SCA , DAST Security scans
on:
  push:
    branches:
      - main

run-name: "Java-Project, ${{ github.actor }}, Event: ${{ github.event_name }}"

defaults:
  run:
    shell: bash

jobs:
  trivy_file_scan:
    runs-on: ubuntu-22.04
    container: 
      image: aquasec/trivy:latest
      options: --entrypoint [""]
    steps:
      - run: |
          trivy fs --format table -o fs-scan.html --scanners vuln,misconfig --severity HIGH,CRITICAL .
          trivy fs --format json -o fs-scan.json --scanners vuln,misconfig --severity HIGH,CRITICAL .
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: |
            fs-scan.html
            fs-scan.json
  SAST_job_sonar:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with mvn for SAST "Static Application Security Testing"
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=sidhugithubaction_java-project -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN -Dsonar.organization=sidhugithubaction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SCA_job_security:
    runs-on: ubuntu-22.04
    needs: SAST_job_sonar
    name: Run the SCA Scan using SNYK
    steps:
      - uses: actions/checkout@v4
      - name: Run SYNK to check for Vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

