name: Build Code, Run unit test, Run SAST, SCA , DAST Security scans
on:
  push:
    branches:
      - main

run-name: "Java-Project, ${{ github.actor }}, Event: ${{ github.event_name }}"

defaults:
  run:
    shell: bash

jobs:
  SAST_job_sonar:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with mvn for SAST "Static Application Security Testing"
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=sidhugithubaction_java-project -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN -Dsonar.organization=sidhugithubaction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SCA_job_security:
    runs-on: ubuntu-22.04
    needs: SAST_job_sonar
    name: Run the SCA Scan using SNYK
    steps:
      - uses: actions/checkout@v4
      - name: Run SYNK to check for Vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  ZAP_SCAN_DAST_scan:
    runs-on: ubuntu-22.04
    needs: SCA_job_security
    name: RUN DAST Dynamic application Security testing on webapp
    steps:
      - uses: actions/checkout@v4
      - name: DAST and ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          # docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org/'
          # rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

